version: '3.2'
services:
    zookeeper:
        image: zookeeper
        hostname: zookeeper
        restart: always
        volumes:
            - ./zoo1/data:/data
            - ./zoo1/datalog:/datalog
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zookeeper:2888:3888 server.2=zookeeper-replica:2888:3888

    zookeeper-replica:
        image: zookeeper
        hostname: zookeeper-replica
        restart: always
        volumes:
            - ./zoo2/data:/data
            - ./zoo2/datalog:/datalog
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zookeeper:2888:3888 server.2=zookeeper-replica:2888:3888

    zkclientsample:
        image: ecdevops.eu/zkclientsample
        ports:
          - 8080
        links:
          - zookeeper
        depends_on:
          - zookeeper
        environment:
          SPRING_PROFILES_ACTIVE: docker

    zkclientsample_no_healthcheck:
      image: ecdevops.eu/zkclientsample
      ports:
      - 8080
      links:
      - zookeeper
      depends_on:
      - zookeeper
      environment:
        SPRING_PROFILES_ACTIVE: docker,no_healthcheck

    zkclientsample_unhealth:
      image: ecdevops.eu/zkclientsample
      ports:
      - 8080
      links:
      - zookeeper
      depends_on:
      - zookeeper
      environment:
        SPRING_PROFILES_ACTIVE: docker,failing-healthcheck

    zkapachebridge-rewritemap:
      image: ecdevops.eu/zk-apache-bridge-docker-rewritemap
      ports:
        - 80:80
        - 9090:8080
        - 5005:5005
      links:
        - zookeeper
        - zkclientsample
      depends_on:
        - zookeeper

    zkapachebridge-loadbalancer:
      image: ecdevops.eu/zk-apache-bridge-docker-loadbalancer
      ports:
        - 8080:80
        - 9091:8080
        - 5006:5005
      links:
        - zookeeper
        - zkclientsample
      depends_on:
        - zookeeper
