spring:
  application:
    name: zk-apache-bridge
  cloud:
    zookeeper:
      discovery:
        enabled: true
        register: true
      connect-string: localhost:2181
      max-retries: 1
zkapachebridge:
  healthcheck:
    enabled: true
    interval: 20000
    timeout:
      socket: 2000
      connect: 2000
      connectionRequest: 2000

  urls:
    prefix: services/
  rewritemap:
    active: true
    path: /etc/apache2/maps/apimap.map
  loadbalancer:
    active: false
    path: /etc/apache2/maps/lbconfig.conf
    template: /loadbalancer-config.ftl
    apache-reload: apachectl graceful



---
spring:
  profiles: docker
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
