spring:
  application:
    name: zk-client-sample
  cloud:
    zookeeper:
      discovery:
        enabled: true
        metadata:
          healthcheck:
            enabled: true
            endpoint: /actuator/health
      connect-string: localhost:2181

---
spring:
  profiles: docker
  cloud:
    zookeeper:
      connect-string: zookeeper:2181

---
spring:
  profiles: no-healthcheck
  cloud:
    zookeeper:
      discovery:
        metadata:
          healthcheck:
            enabled: false
            endpoint: /never-called
---
spring:
  profiles: failing-healthcheck
  cloud:
    zookeeper:
      discovery:
        metadata:
          healthcheck:
            enabled: true
            endpoint: /unhealthy
